[package]
name = "arrow_convert"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
repository.workspace = true
description = "Convert between nested rust types and Arrow with arrow"

[dependencies]
arrow = "51.0"
arrow_convert_derive = { version = "0.6.0", path = "../arrow_convert_derive", optional = true }
half = { version = "2.1", default-features = false }
chrono = { version = "0.4", default_features = false, features = ["std"] }
err-derive = "0.3"

[dev-dependencies]
arrow_convert_derive = { version = "0.6.0", path = "../arrow_convert_derive" }
criterion = "0.5"
trybuild = "1.0"

[features]
default = ["derive"]
derive = ["arrow_convert_derive"]

[lib]
bench = false

[[bench]]
name = "bench"
harness = false
