[workspace]
resolver = "2"
members = [
    "arrow_convert",
    "arrow_convert_derive",
    "examples/simple"
]

[workspace.package]
authors = [
  "Swoorup Joshi <swoorupj@gmail.com>",
  "Jorge Leitao <jorgecarleitao@gmail.com>",
  "Chandra Penke <chandrapenke@gmail.com>",
]
edition = "2021"
license = "Apache-2.0 OR MIT"
keywords = ["Arrow", "arrow"]
repository = "https://github.com/Swoorup/arrow-convert"

[workspace.dependencies]
# workspace crates
arrow_convert = { path = "arrow_convert", version = "0.6.5" }
arrow_convert_derive = { path = "arrow_convert_derive", version = "0.6.5" }

arrow = "52.0"
chrono = { version = "0.4", default-features = false }
criterion = "0.5"
err-derive = "0.3"
half = { version = "2.1", default-features = false }
proc-macro-error = "1"
proc-macro2 = "1"
quote = "1"
syn = "2"
trybuild = "1.0"
pretty_assertions = "1.4"
